## Use workflows from ninenines/ci.erlang.mk to test Cowlib.

name: Check Cowlib

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
      ## Every Monday at 2am.
      - cron: 0 2 * * 1

env:
  CI_ERLANG_MK: 1

jobs:
  check:
    name: Check
    uses: ninenines/ci.erlang.mk/.github/workflows/ci.yaml@master

  perfs:
    name: Run performance tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install latest Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: '> 0'

    - name: Run perfs
      run: make perfs
